name: Github Action Deno
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github\/**' # Ignore changes to files in the .github folder
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0' # Every Sunday at 6:15 UTC
  workflow_dispatch: # Manually triggered
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions\/checkout@v2
      - name: Print trigger event name
      #  run: echo \"Trigger event: ${{ github.event_name }}\"
      - name: Print current branch name
       # run: echo \"Branch name: ${{ github.ref }}\"
      - name: List all files
        run: ls -R
