name: Github Action Deno
on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github\/**' # Ignore changes to files in the .github folder
  pull_request:
    branches:
      - main
  schedule:
    - cron: '15 6 * * 0' # Every Sunday at 6:15 UTC
  workflow_dispatch: # Manually triggered
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions\/checkout@v2
      - name: Print trigger event name
        run: echo "Trigger event:"
      - name: Print current branch name
        run: echo "Branch name:"
      - name: List all files
        run: ls -R
